# Generated by Django 3.2.8 on 2021-10-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211031_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='lastname',
        ),
    ]
